name: Java CI

on: 
  push:
    branches:
      - '**'
    tags:
      - none  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3.1.0
      with:
        fetch-depth: 1
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3.3.0
      with:
        distribution: temurin
        java-version: 17
        cache: maven
        
    - name: Build with Maven
      run: |
        mvn --batch-mode --update-snapshots clean deploy
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}  
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}  
    