name: Java CI

on: 
  push:
    branches:
      - '**'
    tags:
      - none  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 1
    
    - name: Set up JDK 21
      uses: actions/setup-java@v5.0.0
      with:
        distribution: temurin
        java-version: 21
        cache: maven
        
    - name: Build with Maven
      run: |
        mvn --batch-mode --update-snapshots clean deploy
      env:
        CENTRAL_PORTAL_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}  
        CENTRAL_PORTAL_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}  
    