name: Release to Maven Central

on: 
  push:
    tags: 
      - '**'
    branches:
      - none  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 1
    
    - name: Set up JDK 21
      uses: actions/setup-java@v5.0.0
      with:
        distribution: temurin
        java-version: 21
        cache: maven
        
    - name: Build Maven release
      run: |
        mvn --batch-mode clean deploy -Prelease
      env:
        CENTRAL_PORTAL_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}  
        CENTRAL_PORTAL_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}  
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        MAVEN_GPG_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
